### ISSUE TITLE
UI: Very High: Login with invalid password

### ISSUE THREAD

**Issue by ChetanaKoulagi** [LetsTagOn/LetsTagOnThoughtClan#14]
1. There is a message saying invalid credentials, but the home screen refreshes and seems to login when I click on letstagon home page.

**Comment by shrikan** [comment]
its not issue with logging in, it is just refreshing and is getting redirected to http://ec2-54-187-229-255.us-west-2.compute.amazonaws.com:8080/#/, while on startup the landing page is http://ec2-54-187-229-255.us-west-2.compute.amazonaws.com:8080/#/welcome.
So that concludes it is not an issue of logging in, but an issue with redirection after logging in. it is getting redirected whether or not the login was successful. that check should be implemeneted both in front end and back end.

**Comment by ChetanaKoulagi** [comment]
This is fixed by redirecting the page.
