### ISSUE TITLE
Forgot password link

### ISSUE THREAD

**Issue by ChetanaKoulagi** [LetsTagOn/LetsTagOnThoughtClan#44]
When clicked on the link sent to reset pwd when the user says Forgot password, it is redirecting to landing page and not yet showing window to enter new password.

**Comment by Viswa-Vinod** [comment]
It is showing me the window to enter password. I am unable to replicate the issue. This seems to be working.

**Comment by Viswa-Vinod** [comment]
sorry...I misunderstood. Let me check again.

**Comment by Viswa-Vinod** [comment]
I am seeing errors when I click on the submit button in the forgot password form. I have informed Ravi of the errors. They seem related to authenticating with the email server. Once that is cleared I will be able to investigate further.

**Comment by Viswa-Vinod** [comment]
Although I am not able to replicate the this issue because of the problem mentioned in the above comment, I think I have figured out the reason why it did not work for you. There was a missing html page change_password.html. I have found that page and placed it in the project folder structure. It should be resolved now. Again, once I push all the changes to the repo, please test and confirm.

**Comment by ChetanaKoulagi** [comment]
This seems to be fixed now.
